INSERT INTO LMS_TRNG_DTLS (TRNG_ID, MODULE_NAME, MODULE_DTLS, MODULE_DURATION, TRAINER_ID, MODULE_PATH, SEQ_ID, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES
(1, 'Introduction to Communication', 'Understanding the basics of business communication', 60, 1, '/courses/comm/intro.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(1, 'Verbal Communication Skills', 'Mastering verbal communication in business', 90, 1, '/courses/comm/verbal.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(1, 'Non-Verbal Cues', 'Understanding body language and non-verbal signals', 45, 2, '/courses/comm/nonverbal.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(1, 'Presentation Basics', 'Creating and delivering basic presentations', 120, 1, '/courses/comm/presentation.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(1, 'Communication Barriers', 'Identifying and overcoming communication barriers', 60, 2, '/courses/comm/barriers.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(1, 'Practice Session', 'Hands-on practice with real scenarios', 90, 1, '/courses/comm/practice.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Email Structure and Format', 'Understanding professional email structure', 45, 2, '/courses/email/structure.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Writing Clear Subject Lines', 'Crafting effective email subjects', 30, 2, '/courses/email/subjects.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Email Tone and Style', 'Maintaining professional tone in emails', 60, 1, '/courses/email/tone.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Common Email Mistakes', 'Avoiding common pitfalls in email writing', 45, 2, '/courses/email/mistakes.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Email Templates', 'Using templates for efficiency', 30, 1, '/courses/email/templates.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Email Etiquette', 'Professional email etiquette guidelines', 60, 2, '/courses/email/etiquette.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Practice Writing', 'Writing practice emails', 90, 1, '/courses/email/practice.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Fundamentals of Listening', 'Understanding active listening principles', 60, 3, '/courses/listening/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Listening Techniques', 'Advanced listening techniques', 75, 3, '/courses/listening/techniques.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Overcoming Distractions', 'Managing distractions while listening', 45, 2, '/courses/listening/distractions.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Empathetic Listening', 'Developing empathy through listening', 90, 3, '/courses/listening/empathy.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Feedback and Clarification', 'Providing feedback and seeking clarification', 60, 2, '/courses/listening/feedback.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Role Play Exercises', 'Practicing active listening in scenarios', 120, 3, '/courses/listening/roleplay.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Workplace Etiquette Basics', 'Understanding professional workplace behavior', 60, 1, '/courses/etiquette/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Meeting Etiquette', 'Professional behavior in meetings', 45, 1, '/courses/etiquette/meetings.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Dress Code and Appearance', 'Professional appearance standards', 30, 2, '/courses/etiquette/dress.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Office Communication Norms', 'Communication standards in the office', 60, 1, '/courses/etiquette/communication.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Networking Etiquette', 'Professional networking guidelines', 75, 2, '/courses/etiquette/networking.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Time Management Principles', 'Core principles of managing time', 60, 3, '/courses/time/principles.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Prioritization Techniques', 'Learning to prioritize tasks effectively', 90, 3, '/courses/time/prioritization.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Using Calendar Tools', 'Mastering calendar and scheduling tools', 45, 2, '/courses/time/calendar.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Avoiding Procrastination', 'Strategies to overcome procrastination', 60, 3, '/courses/time/procrastination.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Delegation Skills', 'Learning when and how to delegate', 75, 2, '/courses/time/delegation.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Time Management Tools', 'Using software for time management', 45, 3, '/courses/time/tools.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Creating Daily Schedules', 'Building effective daily routines', 60, 2, '/courses/time/schedules.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(6, 'Banking Systems Overview', 'Understanding modern banking systems', 90, 4, '/courses/banking/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(6, 'Account Types and Management', 'Different types of bank accounts', 60, 4, '/courses/banking/accounts.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(6, 'Transaction Processing', 'How banking transactions are processed', 120, 5, '/courses/banking/transactions.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(6, 'Banking Regulations', 'Understanding banking compliance and regulations', 90, 4, '/courses/banking/regulations.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(6, 'Customer Service in Banking', 'Providing excellent banking customer service', 75, 5, '/courses/banking/service.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(6, 'Banking Software Tools', 'Using core banking software', 120, 4, '/courses/banking/software.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(7, 'Trading Basics', 'Introduction to financial trading concepts', 90, 5, '/courses/trading/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(7, 'Market Types', 'Understanding different financial markets', 60, 5, '/courses/trading/markets.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(7, 'Trading Instruments', 'Overview of trading instruments', 120, 4, '/courses/trading/instruments.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(7, 'Market Analysis', 'Basic market analysis techniques', 90, 5, '/courses/trading/analysis.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(7, 'Risk Management in Trading', 'Understanding trading risks', 75, 4, '/courses/trading/risk.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(7, 'Trading Platform Demo', 'Hands-on with trading platforms', 120, 5, '/courses/trading/platform.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Corporate Finance Overview', 'Introduction to corporate finance', 90, 4, '/courses/finance/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Financial Statements', 'Understanding financial statements', 120, 4, '/courses/finance/statements.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Budgeting and Forecasting', 'Creating budgets and forecasts', 90, 5, '/courses/finance/budgeting.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Capital Structure', 'Understanding capital structure decisions', 75, 4, '/courses/finance/capital.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Working Capital Management', 'Managing working capital effectively', 60, 5, '/courses/finance/working_capital.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Financial Ratios', 'Key financial ratios and metrics', 90, 4, '/courses/finance/ratios.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(8, 'Case Studies', 'Real-world finance case studies', 120, 5, '/courses/finance/cases.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(9, 'Supply Chain Overview', 'Understanding supply chain fundamentals', 90, 6, '/courses/supply/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(9, 'Procurement Process', 'Managing procurement in supply chain', 75, 6, '/courses/supply/procurement.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(9, 'Inventory Management', 'Basics of inventory management', 90, 5, '/courses/supply/inventory.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(9, 'Logistics and Distribution', 'Understanding logistics operations', 120, 6, '/courses/supply/logistics.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(9, 'Supplier Relationship Management', 'Managing supplier relationships', 60, 5, '/courses/supply/suppliers.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(9, 'Supply Chain Technology', 'Software tools for supply chain', 90, 6, '/courses/supply/technology.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(10, 'Customer Service Fundamentals', 'Core principles of customer service', 60, 7, '/courses/service/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(10, 'Communication with Customers', 'Effective customer communication', 75, 7, '/courses/service/communication.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(10, 'Handling Complaints', 'Managing customer complaints', 90, 6, '/courses/service/complaints.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(10, 'Service Recovery', 'Recovering from service failures', 60, 7, '/courses/service/recovery.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(10, 'CRM Systems', 'Using customer relationship management tools', 120, 6, '/courses/service/crm.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(10, 'Customer Satisfaction Metrics', 'Measuring customer satisfaction', 45, 7, '/courses/service/metrics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Java Basics', 'Introduction to Java syntax and concepts', 120, 8, '/courses/java/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Variables and Data Types', 'Understanding Java variables and types', 90, 8, '/courses/java/variables.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Control Flow', 'If statements, loops, and control structures', 90, 9, '/courses/java/control.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Object-Oriented Programming', 'OOP concepts in Java', 120, 8, '/courses/java/oop.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Classes and Objects', 'Creating classes and objects in Java', 90, 9, '/courses/java/classes.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Exception Handling', 'Managing exceptions in Java', 75, 8, '/courses/java/exceptions.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'Java Collections', 'Working with Java collections framework', 120, 9, '/courses/java/collections.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(11, 'First Java Program', 'Building your first Java application', 90, 8, '/courses/java/first_program.mp4', 8, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'Introduction to Databases', 'Understanding relational databases', 60, 10, '/courses/sql/intro.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'SQL SELECT Statements', 'Basic SELECT queries', 90, 10, '/courses/sql/select.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'Filtering with WHERE', 'Using WHERE clause for filtering', 75, 9, '/courses/sql/where.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'JOIN Operations', 'Joining tables in SQL', 120, 10, '/courses/sql/joins.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'Aggregate Functions', 'Using COUNT, SUM, AVG, etc.', 90, 9, '/courses/sql/aggregate.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'GROUP BY and HAVING', 'Grouping and filtering groups', 75, 10, '/courses/sql/groupby.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(12, 'INSERT, UPDATE, DELETE', 'Data manipulation operations', 90, 9, '/courses/sql/dml.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Oracle Database Architecture', 'Understanding Oracle architecture', 90, 10, '/courses/oracle/architecture.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Installing Oracle', 'Oracle database installation', 120, 11, '/courses/oracle/installation.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Oracle SQL Developer', 'Using SQL Developer tool', 60, 10, '/courses/oracle/sqldeveloper.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Oracle Data Types', 'Understanding Oracle data types', 75, 11, '/courses/oracle/datatypes.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Creating Tables in Oracle', 'Table creation in Oracle', 90, 10, '/courses/oracle/tables.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Oracle Constraints', 'Working with constraints', 60, 11, '/courses/oracle/constraints.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(13, 'Basic Queries in Oracle', 'Running queries in Oracle', 90, 10, '/courses/oracle/queries.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Python Installation and Setup', 'Setting up Python environment', 45, 12, '/courses/python/setup.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Python Syntax Basics', 'Understanding Python syntax', 90, 12, '/courses/python/syntax.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Variables and Types', 'Python variables and data types', 75, 11, '/courses/python/variables.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Lists and Tuples', 'Working with lists and tuples', 90, 12, '/courses/python/lists.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Dictionaries and Sets', 'Using dictionaries and sets', 75, 11, '/courses/python/dicts.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Functions in Python', 'Creating and using functions', 90, 12, '/courses/python/functions.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'Python Loops', 'For and while loops in Python', 60, 11, '/courses/python/loops.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(14, 'File Handling', 'Reading and writing files', 75, 12, '/courses/python/files.mp4', 8, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'HTML Basics', 'Introduction to HTML structure', 90, 13, '/courses/web/html.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'HTML Tags and Elements', 'Common HTML tags', 75, 13, '/courses/web/tags.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'HTML Forms', 'Creating forms in HTML', 90, 12, '/courses/web/forms.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'CSS Basics', 'Introduction to CSS', 90, 13, '/courses/web/css.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'CSS Selectors', 'Understanding CSS selectors', 60, 12, '/courses/web/selectors.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'CSS Box Model', 'Understanding the box model', 75, 13, '/courses/web/boxmodel.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(15, 'Building a Simple Webpage', 'Creating your first webpage', 120, 12, '/courses/web/webpage.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(16, 'Building Relationships', 'Developing strong interpersonal skills', 60, 14, '/courses/interpersonal/relationships.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(16, 'Effective Communication', 'Communicating effectively with others', 75, 14, '/courses/interpersonal/communication.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(16, 'Understanding Others', 'Empathy and understanding', 60, 15, '/courses/interpersonal/understanding.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(16, 'Working in Teams', 'Collaborating with team members', 90, 14, '/courses/interpersonal/teams.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(16, 'Giving and Receiving Feedback', 'Feedback techniques', 75, 15, '/courses/interpersonal/feedback.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(16, 'Building Trust', 'Creating trustful relationships', 60, 14, '/courses/interpersonal/trust.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'Understanding Conflict', 'Types and sources of workplace conflict', 60, 15, '/courses/conflict/understanding.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'Conflict Resolution Styles', 'Different approaches to conflict', 75, 15, '/courses/conflict/styles.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'Mediation Techniques', 'Mediating between conflicting parties', 90, 14, '/courses/conflict/mediation.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'De-escalation Strategies', 'Calming tense situations', 60, 15, '/courses/conflict/deescalation.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'Win-Win Solutions', 'Finding mutually beneficial outcomes', 90, 14, '/courses/conflict/winwin.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'Case Studies', 'Real workplace conflict scenarios', 120, 15, '/courses/conflict/cases.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(17, 'Practice Sessions', 'Role-playing conflict scenarios', 90, 14, '/courses/conflict/practice.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(18, 'Team Dynamics', 'Understanding team behavior', 60, 16, '/courses/teamwork/dynamics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(18, 'Team Roles', 'Different roles in effective teams', 75, 16, '/courses/teamwork/roles.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(18, 'Collaboration Tools', 'Using digital collaboration tools', 90, 15, '/courses/teamwork/tools.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(18, 'Building Team Culture', 'Creating positive team culture', 60, 16, '/courses/teamwork/culture.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(18, 'Team Decision Making', 'Making decisions as a team', 90, 15, '/courses/teamwork/decisions.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(18, 'Team Challenges', 'Overcoming common team challenges', 75, 16, '/courses/teamwork/challenges.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(19, 'Understanding Stress', 'What is stress and its impact', 45, 17, '/courses/stress/understanding.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(19, 'Stress Triggers', 'Identifying your stress triggers', 60, 17, '/courses/stress/triggers.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(19, 'Relaxation Techniques', 'Methods to reduce stress', 75, 16, '/courses/stress/relaxation.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(19, 'Work-Life Balance', 'Maintaining healthy work-life balance', 60, 17, '/courses/stress/balance.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(19, 'Mindfulness and Meditation', 'Practicing mindfulness', 90, 16, '/courses/stress/mindfulness.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(19, 'Stress Management Plan', 'Creating your personal stress plan', 60, 17, '/courses/stress/plan.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'SMART Goals', 'Setting specific, measurable goals', 60, 18, '/courses/goals/smart.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'Breaking Down Goals', 'Creating actionable steps', 75, 18, '/courses/goals/breakdown.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'Tracking Progress', 'Monitoring goal achievement', 60, 17, '/courses/goals/tracking.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'Overcoming Obstacles', 'Dealing with setbacks', 90, 18, '/courses/goals/obstacles.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'Accountability Systems', 'Creating accountability', 60, 17, '/courses/goals/accountability.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'Celebrating Success', 'Recognizing achievements', 45, 18, '/courses/goals/celebrating.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(20, 'Long-term Planning', 'Setting long-term career goals', 90, 17, '/courses/goals/longterm.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(21, 'Retail Banking Products', 'Overview of retail products', 90, 19, '/courses/retail/products.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(21, 'Account Opening Process', 'Opening new customer accounts', 75, 19, '/courses/retail/opening.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(21, 'Deposit Operations', 'Managing deposits and withdrawals', 90, 18, '/courses/retail/deposits.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(21, 'Loan Products', 'Understanding retail loan products', 120, 19, '/courses/retail/loans.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(21, 'Credit Cards', 'Credit card products and services', 60, 18, '/courses/retail/cards.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(21, 'Branch Operations', 'Daily branch banking operations', 90, 19, '/courses/retail/branch.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(22, 'Investment Products Overview', 'Types of investment products', 90, 20, '/courses/investment/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(22, 'Stocks and Equities', 'Understanding stock investments', 120, 20, '/courses/investment/stocks.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(22, 'Bonds and Fixed Income', 'Fixed income investment products', 90, 19, '/courses/investment/bonds.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(22, 'Mutual Funds', 'Understanding mutual fund investments', 75, 20, '/courses/investment/mutualfunds.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(22, 'Investment Strategies', 'Basic investment strategies', 90, 19, '/courses/investment/strategies.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(22, 'Portfolio Basics', 'Building investment portfolios', 120, 20, '/courses/investment/portfolio.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(23, 'Risk Types', 'Understanding different types of risk', 75, 1, '/courses/risk/types.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(23, 'Risk Assessment', 'Assessing risk levels', 90, 1, '/courses/risk/assessment.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(23, 'Risk Mitigation', 'Strategies to reduce risk', 90, 20, '/courses/risk/mitigation.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(23, 'Risk Monitoring', 'Tracking and monitoring risks', 60, 1, '/courses/risk/monitoring.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(23, 'Risk Reporting', 'Reporting risk to stakeholders', 75, 20, '/courses/risk/reporting.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(23, 'Case Studies', 'Real-world risk scenarios', 120, 1, '/courses/risk/cases.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Accounting Equation', 'Understanding the basic equation', 60, 2, '/courses/accounting/equation.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Double Entry System', 'Principles of double entry', 90, 2, '/courses/accounting/doubleentry.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Chart of Accounts', 'Setting up chart of accounts', 75, 1, '/courses/accounting/chart.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Journal Entries', 'Recording journal entries', 90, 2, '/courses/accounting/journal.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Ledger Posting', 'Posting to ledgers', 60, 1, '/courses/accounting/ledger.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Trial Balance', 'Preparing trial balance', 75, 2, '/courses/accounting/trial.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(24, 'Financial Statements', 'Creating basic financial statements', 120, 1, '/courses/accounting/statements.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(25, 'Procurement Process Overview', 'Understanding procurement cycle', 90, 3, '/courses/procurement/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(25, 'Requisition Management', 'Managing purchase requisitions', 60, 3, '/courses/procurement/requisition.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(25, 'Vendor Selection', 'Selecting the right vendors', 90, 2, '/courses/procurement/selection.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(25, 'Purchase Orders', 'Creating and managing POs', 75, 3, '/courses/procurement/po.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(25, 'Invoice Processing', 'Processing vendor invoices', 60, 2, '/courses/procurement/invoice.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(25, 'Procurement Systems', 'Using procurement software', 120, 3, '/courses/procurement/systems.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Basics', 'Understanding version control with Git', 90, 4, '/courses/git/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Repository', 'Creating and cloning repositories', 60, 4, '/courses/git/repository.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Commits', 'Making commits and commit messages', 75, 3, '/courses/git/commits.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Branches', 'Working with branches', 90, 4, '/courses/git/branches.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Merge', 'Merging branches', 90, 3, '/courses/git/merge.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Remote', 'Working with remote repositories', 75, 4, '/courses/git/remote.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'Git Workflow', 'Understanding Git workflows', 60, 3, '/courses/git/workflow.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(26, 'GitHub Basics', 'Using GitHub for collaboration', 90, 4, '/courses/git/github.mp4', 8, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'Linux Introduction', 'Overview of Linux operating system', 60, 5, '/courses/linux/intro.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'Linux File System', 'Understanding Linux file system', 90, 5, '/courses/linux/filesystem.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'Basic Linux Commands', 'Essential command line commands', 120, 4, '/courses/linux/commands.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'File Management', 'Creating, moving, and deleting files', 75, 5, '/courses/linux/files.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'User and Permissions', 'Managing users and file permissions', 90, 4, '/courses/linux/permissions.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'Process Management', 'Managing Linux processes', 60, 5, '/courses/linux/processes.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(27, 'Package Management', 'Installing and updating software', 75, 4, '/courses/linux/packages.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(28, 'REST API Concepts', 'Understanding REST architecture', 90, 6, '/courses/api/concepts.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(28, 'HTTP Methods', 'GET, POST, PUT, DELETE operations', 75, 6, '/courses/api/methods.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(28, 'API Endpoints', 'Designing API endpoints', 90, 5, '/courses/api/endpoints.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(28, 'Request and Response', 'Understanding API requests and responses', 60, 6, '/courses/api/reqres.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(28, 'API Testing', 'Testing APIs with tools', 120, 5, '/courses/api/testing.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(28, 'API Documentation', 'Documenting APIs', 60, 6, '/courses/api/documentation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Container Basics', 'Understanding containerization', 75, 7, '/courses/docker/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Docker Installation', 'Installing Docker', 45, 7, '/courses/docker/installation.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Docker Images', 'Working with Docker images', 90, 6, '/courses/docker/images.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Docker Containers', 'Running and managing containers', 90, 7, '/courses/docker/containers.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Dockerfile', 'Creating Dockerfiles', 120, 6, '/courses/docker/dockerfile.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Docker Compose', 'Multi-container applications', 90, 7, '/courses/docker/compose.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(29, 'Docker Networking', 'Container networking basics', 60, 6, '/courses/docker/networking.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(30, 'Cloud Computing Overview', 'Introduction to cloud computing', 60, 8, '/courses/cloud/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(30, 'Cloud Service Models', 'IaaS, PaaS, SaaS explained', 75, 8, '/courses/cloud/models.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(30, 'AWS Introduction', 'Getting started with AWS', 90, 7, '/courses/cloud/aws.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(30, 'EC2 Basics', 'Using AWS EC2 instances', 120, 8, '/courses/cloud/ec2.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(30, 'S3 Storage', 'Working with AWS S3', 60, 7, '/courses/cloud/s3.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(30, 'Cloud Security Basics', 'Understanding cloud security', 90, 8, '/courses/cloud/security.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Advanced Presentation Planning', 'Planning executive presentations', 90, 9, '/courses/advpres/planning.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Data Visualization', 'Creating impactful visualizations', 120, 9, '/courses/advpres/visualization.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Storytelling Techniques', 'Crafting compelling narratives', 90, 8, '/courses/advpres/storytelling.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Handling Q&A', 'Managing questions effectively', 75, 9, '/courses/advpres/qa.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Executive Presence', 'Building executive presence', 60, 8, '/courses/advpres/presence.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Presentation Technology', 'Advanced presentation tools', 90, 9, '/courses/advpres/technology.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(31, 'Practice and Feedback', 'Delivering and refining presentations', 120, 8, '/courses/advpres/practice.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(32, 'Leadership Fundamentals', 'Core leadership principles', 90, 10, '/courses/leadership/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(32, 'Leadership Styles', 'Different leadership approaches', 75, 10, '/courses/leadership/styles.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(32, 'Vision and Strategy', 'Creating and communicating vision', 120, 9, '/courses/leadership/vision.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(32, 'Motivating Teams', 'Inspiring team performance', 90, 10, '/courses/leadership/motivating.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(32, 'Decision Making', 'Making effective leadership decisions', 75, 9, '/courses/leadership/decisions.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(32, 'Developing Others', 'Growing future leaders', 90, 10, '/courses/leadership/developing.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Negotiation Principles', 'Core negotiation concepts', 90, 11, '/courses/negotiation/principles.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Preparation and Planning', 'Preparing for negotiations', 75, 11, '/courses/negotiation/preparation.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Negotiation Tactics', 'Advanced negotiation tactics', 120, 10, '/courses/negotiation/tactics.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Handling Difficult Negotiations', 'Managing challenging situations', 90, 11, '/courses/negotiation/difficult.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Creating Value', 'Finding win-win outcomes', 75, 10, '/courses/negotiation/value.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Closing Deals', 'Finalizing agreements', 60, 11, '/courses/negotiation/closing.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(33, 'Negotiation Simulations', 'Practice negotiation scenarios', 120, 10, '/courses/negotiation/simulations.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(34, 'Understanding Change', 'Why organizations change', 60, 12, '/courses/change/understanding.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(34, 'Change Models', 'Change management frameworks', 90, 12, '/courses/change/models.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(34, 'Leading Change', 'Guiding organizational change', 120, 11, '/courses/change/leading.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(34, 'Overcoming Resistance', 'Managing resistance to change', 90, 12, '/courses/change/resistance.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(34, 'Communication in Change', 'Communicating during transitions', 75, 11, '/courses/change/communication.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(34, 'Sustaining Change', 'Making change stick', 60, 12, '/courses/change/sustaining.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(35, 'What is EI', 'Understanding emotional intelligence', 75, 13, '/courses/ei/what.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(35, 'Self-Awareness', 'Developing self-awareness', 90, 13, '/courses/ei/selfawareness.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(35, 'Self-Regulation', 'Managing emotions effectively', 90, 12, '/courses/ei/selfregulation.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(35, 'Social Awareness', 'Understanding others emotions', 75, 13, '/courses/ei/socialawareness.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(35, 'Relationship Management', 'Building strong relationships', 90, 12, '/courses/ei/relationships.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(35, 'EI in Leadership', 'Applying EI as a leader', 120, 13, '/courses/ei/leadership.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(36, 'Corporate Banking Overview', 'Understanding corporate banking', 90, 14, '/courses/corpbank/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(36, 'Corporate Lending', 'Corporate loan products', 120, 14, '/courses/corpbank/lending.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(36, 'Cash Management', 'Corporate cash management services', 90, 13, '/courses/corpbank/cash.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(36, 'Trade Finance', 'International trade finance', 120, 14, '/courses/corpbank/trade.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(36, 'Relationship Management', 'Managing corporate clients', 75, 13, '/courses/corpbank/relationship.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(36, 'Credit Analysis', 'Corporate credit analysis', 90, 14, '/courses/corpbank/credit.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Derivatives Overview', 'Introduction to derivatives', 90, 15, '/courses/derivatives/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Futures Contracts', 'Understanding futures', 120, 15, '/courses/derivatives/futures.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Options Trading', 'Call and put options', 120, 14, '/courses/derivatives/options.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Swaps', 'Interest rate and currency swaps', 90, 15, '/courses/derivatives/swaps.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Hedging Strategies', 'Using derivatives for hedging', 90, 14, '/courses/derivatives/hedging.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Pricing Models', 'Derivatives pricing basics', 120, 15, '/courses/derivatives/pricing.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(37, 'Risk Management', 'Managing derivative risks', 75, 14, '/courses/derivatives/risk.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(38, 'Financial Statement Analysis', 'Analyzing financial statements', 120, 16, '/courses/finanalysis/statements.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(38, 'Ratio Analysis', 'Financial ratios and interpretation', 90, 16, '/courses/finanalysis/ratios.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(38, 'Cash Flow Analysis', 'Analyzing cash flows', 90, 15, '/courses/finanalysis/cashflow.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(38, 'Valuation Techniques', 'Company valuation methods', 120, 16, '/courses/finanalysis/valuation.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(38, 'Industry Analysis', 'Analyzing industry trends', 75, 15, '/courses/finanalysis/industry.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(38, 'Financial Modeling', 'Building financial models', 120, 16, '/courses/finanalysis/modeling.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(39, 'Logistics Fundamentals', 'Understanding logistics operations', 90, 17, '/courses/logistics/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(39, 'Transportation Management', 'Managing transportation', 90, 17, '/courses/logistics/transportation.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(39, 'Warehousing', 'Warehouse management', 120, 16, '/courses/logistics/warehousing.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(39, 'Distribution Networks', 'Designing distribution networks', 75, 17, '/courses/logistics/distribution.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(39, 'Logistics Technology', 'Using logistics software', 90, 16, '/courses/logistics/technology.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(39, 'Performance Metrics', 'Measuring logistics performance', 60, 17, '/courses/logistics/metrics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(40, 'Treasury Functions', 'Overview of treasury operations', 90, 18, '/courses/treasury/functions.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(40, 'Cash Management', 'Managing corporate cash', 120, 18, '/courses/treasury/cash.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(40, 'Liquidity Management', 'Ensuring adequate liquidity', 90, 17, '/courses/treasury/liquidity.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(40, 'Foreign Exchange', 'Managing FX risk', 75, 18, '/courses/treasury/forex.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(40, 'Investment Management', 'Short-term investments', 90, 17, '/courses/treasury/investment.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(40, 'Treasury Systems', 'Using treasury management systems', 120, 18, '/courses/treasury/systems.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'Spring Framework Basics', 'Introduction to Spring', 120, 19, '/courses/advjava/spring.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'Dependency Injection', 'Understanding DI in Spring', 90, 19, '/courses/advjava/di.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'Spring Boot', 'Building apps with Spring Boot', 120, 18, '/courses/advjava/springboot.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'Design Patterns', 'Java design patterns', 120, 19, '/courses/advjava/patterns.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'JPA and Hibernate', 'Object-relational mapping', 90, 18, '/courses/advjava/jpa.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'RESTful Services', 'Building REST APIs in Java', 120, 19, '/courses/advjava/rest.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'Testing in Java', 'Unit and integration testing', 90, 18, '/courses/advjava/testing.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(41, 'Best Practices', 'Java coding best practices', 75, 19, '/courses/advjava/bestpractices.mp4', 8, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Database Design Principles', 'Designing efficient databases', 120, 20, '/courses/advdb/design.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Normalization', 'Database normalization techniques', 90, 20, '/courses/advdb/normalization.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Indexing Strategies', 'Creating and using indexes', 90, 19, '/courses/advdb/indexing.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Query Optimization', 'Optimizing SQL queries', 120, 20, '/courses/advdb/optimization.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Execution Plans', 'Understanding query plans', 75, 19, '/courses/advdb/plans.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Performance Tuning', 'Database performance tuning', 120, 20, '/courses/advdb/tuning.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(42, 'Monitoring Tools', 'Using database monitoring tools', 60, 19, '/courses/advdb/monitoring.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'PL/SQL Basics', 'Introduction to PL/SQL', 90, 1, '/courses/plsql/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'Stored Procedures', 'Creating stored procedures', 120, 1, '/courses/plsql/procedures.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'Functions', 'PL/SQL functions', 90, 20, '/courses/plsql/functions.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'Triggers', 'Database triggers in Oracle', 90, 1, '/courses/plsql/triggers.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'Packages', 'Creating and using packages', 120, 20, '/courses/plsql/packages.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'Exception Handling', 'Managing errors in PL/SQL', 75, 1, '/courses/plsql/exceptions.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(43, 'Performance Optimization', 'Optimizing PL/SQL code', 90, 20, '/courses/plsql/performance.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Pandas Library', 'Introduction to Pandas', 90, 2, '/courses/pydata/pandas.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Data Loading', 'Loading data from various sources', 75, 2, '/courses/pydata/loading.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Data Cleaning', 'Cleaning and preprocessing data', 120, 1, '/courses/pydata/cleaning.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Data Transformation', 'Transforming and reshaping data', 90, 2, '/courses/pydata/transformation.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Data Visualization', 'Visualizing data with matplotlib', 90, 1, '/courses/pydata/visualization.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Statistical Analysis', 'Basic statistical analysis', 120, 2, '/courses/pydata/statistics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'NumPy Arrays', 'Working with NumPy', 75, 1, '/courses/pydata/numpy.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(44, 'Real-world Project', 'End-to-end data analysis project', 120, 2, '/courses/pydata/project.mp4', 8, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'Modern JavaScript', 'ES6+ features', 90, 3, '/courses/react/modernjs.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'React Basics', 'Introduction to React', 120, 3, '/courses/react/basics.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'Components', 'Creating React components', 90, 2, '/courses/react/components.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'State and Props', 'Managing component state', 90, 3, '/courses/react/state.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'React Hooks', 'Using React hooks', 120, 2, '/courses/react/hooks.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'React Router', 'Implementing routing', 75, 3, '/courses/react/router.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'API Integration', 'Fetching data from APIs', 90, 2, '/courses/react/api.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(45, 'Building an App', 'Complete React application', 120, 3, '/courses/react/app.mp4', 8, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Coaching Fundamentals', 'Core coaching principles', 90, 4, '/courses/coaching/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Coaching Models', 'GROW and other coaching models', 75, 4, '/courses/coaching/models.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Active Listening', 'Listening skills for coaches', 90, 3, '/courses/coaching/listening.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Powerful Questions', 'Asking effective coaching questions', 90, 4, '/courses/coaching/questions.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Giving Feedback', 'Providing developmental feedback', 75, 3, '/courses/coaching/feedback.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Goal Setting', 'Setting coaching goals', 60, 4, '/courses/coaching/goals.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(46, 'Practice Sessions', 'Coaching practice and role plays', 120, 3, '/courses/coaching/practice.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Crisis Definition', 'What constitutes a crisis', 60, 5, '/courses/crisis/definition.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Crisis Response Plan', 'Creating crisis response plans', 90, 5, '/courses/crisis/plan.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Spokesperson Training', 'Being an effective spokesperson', 120, 4, '/courses/crisis/spokesperson.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Message Development', 'Crafting crisis messages', 75, 5, '/courses/crisis/messages.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Media Relations', 'Working with media during crisis', 90, 4, '/courses/crisis/media.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Social Media Management', 'Managing social media in crisis', 60, 5, '/courses/crisis/social.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(47, 'Crisis Simulations', 'Practice crisis scenarios', 120, 4, '/courses/crisis/simulations.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(48, 'Performance Goals', 'Setting performance objectives', 75, 6, '/courses/perfmgmt/goals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(48, 'Performance Metrics', 'Defining success metrics', 90, 6, '/courses/perfmgmt/metrics.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(48, 'Continuous Feedback', 'Providing ongoing feedback', 90, 5, '/courses/perfmgmt/feedback.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(48, 'Performance Reviews', 'Conducting effective reviews', 120, 6, '/courses/perfmgmt/reviews.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(48, 'Development Plans', 'Creating development plans', 75, 5, '/courses/perfmgmt/development.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(48, 'Managing Underperformance', 'Addressing poor performance', 90, 6, '/courses/perfmgmt/underperformance.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(49, 'Cultural Dimensions', 'Understanding cultural differences', 90, 7, '/courses/cultural/dimensions.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(49, 'Cross-Cultural Communication', 'Communicating across cultures', 75, 7, '/courses/cultural/communication.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(49, 'Cultural Stereotypes', 'Avoiding stereotypes', 60, 6, '/courses/cultural/stereotypes.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(49, 'Building Cultural Awareness', 'Developing cultural sensitivity', 90, 7, '/courses/cultural/awareness.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(49, 'Global Teams', 'Working in global teams', 90, 6, '/courses/cultural/teams.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(49, 'Cultural Adaptation', 'Adapting to new cultures', 75, 7, '/courses/cultural/adaptation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Principles of Influence', 'Understanding influence psychology', 90, 8, '/courses/influence/principles.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Building Credibility', 'Establishing trust and credibility', 75, 8, '/courses/influence/credibility.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Persuasive Communication', 'Communicating persuasively', 90, 7, '/courses/influence/communication.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Influencing Without Authority', 'Influence without formal power', 120, 8, '/courses/influence/noauthority.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Stakeholder Influence', 'Influencing key stakeholders', 90, 7, '/courses/influence/stakeholders.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Ethical Influence', 'Using influence ethically', 60, 8, '/courses/influence/ethics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(50, 'Practice Scenarios', 'Applying influence techniques', 90, 7, '/courses/influence/practice.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(51, 'Credit Risk Fundamentals', 'Understanding credit risk', 90, 9, '/courses/credit/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(51, 'Credit Analysis Techniques', 'Analyzing creditworthiness', 120, 9, '/courses/credit/analysis.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(51, 'Financial Statements Review', 'Reviewing financial statements for credit', 90, 8, '/courses/credit/statements.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(51, 'Risk Rating Models', 'Credit risk rating methodologies', 120, 9, '/courses/credit/rating.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(51, 'Collateral Evaluation', 'Evaluating loan collateral', 75, 8, '/courses/credit/collateral.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(51, 'Credit Documentation', 'Credit documentation requirements', 60, 9, '/courses/credit/documentation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(52, 'Portfolio Theory', 'Modern portfolio theory basics', 120, 10, '/courses/portfolio/theory.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(52, 'Asset Allocation', 'Strategic asset allocation', 90, 10, '/courses/portfolio/allocation.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(52, 'Diversification Strategies', 'Portfolio diversification', 90, 9, '/courses/portfolio/diversification.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(52, 'Rebalancing', 'Portfolio rebalancing techniques', 75, 10, '/courses/portfolio/rebalancing.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(52, 'Risk-Return Analysis', 'Analyzing risk and return', 120, 9, '/courses/portfolio/riskreturn.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(52, 'Performance Measurement', 'Measuring portfolio performance', 90, 10, '/courses/portfolio/performance.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(53, 'IFRS Standards', 'International Financial Reporting Standards', 120, 11, '/courses/reporting/ifrs.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(53, 'GAAP Standards', 'Generally Accepted Accounting Principles', 120, 11, '/courses/reporting/gaap.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(53, 'Consolidation', 'Consolidated financial statements', 90, 10, '/courses/reporting/consolidation.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(53, 'Revenue Recognition', 'Revenue recognition principles', 90, 11, '/courses/reporting/revenue.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(53, 'Disclosure Requirements', 'Financial statement disclosures', 75, 10, '/courses/reporting/disclosure.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(53, 'Reporting Tools', 'Using financial reporting software', 60, 11, '/courses/reporting/tools.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(54, 'Vendor Selection Criteria', 'Evaluating and selecting vendors', 90, 12, '/courses/vendor/selection.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(54, 'Contract Negotiation', 'Negotiating vendor contracts', 120, 12, '/courses/vendor/negotiation.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(54, 'Performance Monitoring', 'Monitoring vendor performance', 75, 11, '/courses/vendor/monitoring.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(54, 'Vendor Risk Management', 'Managing vendor-related risks', 90, 12, '/courses/vendor/risk.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(54, 'Relationship Management', 'Building vendor partnerships', 60, 11, '/courses/vendor/relationship.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(54, 'Vendor Scorecards', 'Creating vendor scorecards', 75, 12, '/courses/vendor/scorecards.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(55, 'Regulatory Framework', 'Understanding financial regulations', 90, 13, '/courses/compliance/framework.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(55, 'AML and KYC', 'Anti-Money Laundering and Know Your Customer', 120, 13, '/courses/compliance/aml.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(55, 'Data Privacy', 'GDPR and data privacy compliance', 90, 12, '/courses/compliance/privacy.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(55, 'Audit Readiness', 'Preparing for regulatory audits', 75, 13, '/courses/compliance/audit.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(55, 'Compliance Reporting', 'Regulatory reporting requirements', 90, 12, '/courses/compliance/reporting.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(55, 'Risk Assessment', 'Compliance risk assessment', 60, 13, '/courses/compliance/risk.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'Microservices Fundamentals', 'Understanding microservices architecture', 120, 14, '/courses/microservices/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'Service Design', 'Designing microservices', 90, 14, '/courses/microservices/design.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'API Gateway', 'Implementing API gateways', 90, 13, '/courses/microservices/gateway.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'Service Discovery', 'Service discovery patterns', 75, 14, '/courses/microservices/discovery.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'Inter-Service Communication', 'Communication between services', 90, 13, '/courses/microservices/communication.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'Data Management', 'Managing data in microservices', 120, 14, '/courses/microservices/data.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(56, 'Deployment Patterns', 'Microservices deployment', 90, 13, '/courses/microservices/deployment.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(57, 'DevOps Culture', 'Understanding DevOps philosophy', 60, 15, '/courses/devops/culture.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(57, 'CI/CD Pipelines', 'Building CI/CD pipelines', 120, 15, '/courses/devops/cicd.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(57, 'Infrastructure as Code', 'Managing infrastructure with code', 90, 14, '/courses/devops/iac.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(57, 'Configuration Management', 'Managing configurations', 75, 15, '/courses/devops/config.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(57, 'Monitoring and Logging', 'Application monitoring and logging', 90, 14, '/courses/devops/monitoring.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(57, 'Automation Tools', 'Using DevOps automation tools', 120, 15, '/courses/devops/automation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'AWS EC2', 'Working with EC2 instances', 120, 16, '/courses/awscloud/ec2.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'AWS S3', 'Using S3 storage service', 90, 16, '/courses/awscloud/s3.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'AWS RDS', 'Relational Database Service', 90, 15, '/courses/awscloud/rds.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'AWS Lambda', 'Serverless computing with Lambda', 120, 16, '/courses/awscloud/lambda.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'AWS VPC', 'Virtual Private Cloud networking', 75, 15, '/courses/awscloud/vpc.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'AWS IAM', 'Identity and Access Management', 90, 16, '/courses/awscloud/iam.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(58, 'Cost Optimization', 'Optimizing AWS costs', 60, 15, '/courses/awscloud/cost.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(59, 'OWASP Top 10', 'Understanding common vulnerabilities', 90, 17, '/courses/security/owasp.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(59, 'Secure Coding', 'Writing secure code', 120, 17, '/courses/security/coding.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(59, 'Authentication', 'Implementing authentication', 90, 16, '/courses/security/authentication.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(59, 'Authorization', 'Access control and authorization', 75, 17, '/courses/security/authorization.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(59, 'Encryption', 'Data encryption techniques', 90, 16, '/courses/security/encryption.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(59, 'Security Testing', 'Security testing methodologies', 120, 17, '/courses/security/testing.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(60, 'Agile Principles', 'Understanding agile values and principles', 75, 18, '/courses/agile/principles.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(60, 'Scrum Framework', 'Implementing Scrum', 90, 18, '/courses/agile/scrum.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(60, 'Sprints and Planning', 'Sprint planning and execution', 90, 17, '/courses/agile/sprints.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(60, 'User Stories', 'Writing effective user stories', 60, 18, '/courses/agile/stories.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(60, 'Retrospectives', 'Conducting sprint retrospectives', 75, 17, '/courses/agile/retrospectives.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(60, 'Agile Metrics', 'Measuring agile team performance', 60, 18, '/courses/agile/metrics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(61, 'Executive Leadership Philosophy', 'Leadership at the executive level', 90, 19, '/courses/execleader/philosophy.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(61, 'Strategic Vision', 'Creating organizational vision', 120, 19, '/courses/execleader/vision.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(61, 'Leading Executives', 'Managing senior leadership team', 90, 18, '/courses/execleader/leading.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(61, 'Board Relations', 'Working with board of directors', 120, 19, '/courses/execleader/board.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(61, 'Crisis Leadership', 'Leading during organizational crisis', 90, 18, '/courses/execleader/crisis.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(61, 'Legacy Building', 'Building lasting organizational legacy', 75, 19, '/courses/execleader/legacy.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(62, 'Strategic Analysis', 'Analyzing strategic situations', 120, 20, '/courses/strategy/analysis.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(62, 'Competitive Strategy', 'Developing competitive strategies', 90, 20, '/courses/strategy/competitive.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(62, 'Blue Ocean Strategy', 'Creating uncontested market space', 90, 19, '/courses/strategy/blueocean.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(62, 'Strategic Planning', 'Long-term strategic planning', 120, 20, '/courses/strategy/planning.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(62, 'Strategy Execution', 'Implementing strategic initiatives', 90, 19, '/courses/strategy/execution.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(62, 'Strategic Metrics', 'Measuring strategic success', 75, 20, '/courses/strategy/metrics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(63, 'OD Fundamentals', 'Organizational development basics', 90, 1, '/courses/od/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(63, 'Organizational Assessment', 'Assessing organizational health', 120, 1, '/courses/od/assessment.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(63, 'Change Architecture', 'Designing organizational change', 90, 20, '/courses/od/architecture.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(63, 'Culture Transformation', 'Transforming organizational culture', 120, 1, '/courses/od/culture.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(63, 'Team Development', 'Building high-performance teams', 75, 20, '/courses/od/teams.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(63, 'OD Interventions', 'Implementing OD interventions', 90, 1, '/courses/od/interventions.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(64, 'Board Dynamics', 'Understanding board dynamics', 90, 2, '/courses/boardcomm/dynamics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(64, 'Board Presentations', 'Preparing board presentations', 120, 2, '/courses/boardcomm/presentations.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(64, 'Financial Communication', 'Communicating financial results', 90, 1, '/courses/boardcomm/financial.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(64, 'Strategy Communication', 'Presenting strategic initiatives', 120, 2, '/courses/boardcomm/strategy.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(64, 'Crisis Communication', 'Communicating during crises', 75, 1, '/courses/boardcomm/crisis.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(64, 'Executive Summary Skills', 'Creating effective executive summaries', 60, 2, '/courses/boardcomm/summary.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(65, 'Global Markets', 'Understanding global markets', 120, 3, '/courses/globalstrat/markets.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(65, 'International Expansion', 'Global expansion strategies', 90, 3, '/courses/globalstrat/expansion.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(65, 'Cross-Border M&A', 'International mergers and acquisitions', 120, 2, '/courses/globalstrat/ma.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(65, 'Global Supply Chains', 'Managing global supply chains', 90, 3, '/courses/globalstrat/supply.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(65, 'Emerging Markets', 'Strategies for emerging markets', 90, 2, '/courses/globalstrat/emerging.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(65, 'Global Risk Management', 'Managing global business risks', 75, 3, '/courses/globalstrat/risk.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'Investment Banking Overview', 'Understanding investment banking', 120, 4, '/courses/invbank/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'M&A Advisory', 'Mergers and acquisitions advisory', 120, 4, '/courses/invbank/ma.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'Capital Raising', 'Equity and debt capital raising', 90, 3, '/courses/invbank/capital.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'Underwriting', 'Securities underwriting process', 120, 4, '/courses/invbank/underwriting.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'Valuation', 'Advanced company valuation', 90, 3, '/courses/invbank/valuation.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'Deal Structuring', 'Structuring investment banking deals', 120, 4, '/courses/invbank/structuring.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(66, 'Pitch Books', 'Creating investment banking pitch books', 75, 3, '/courses/invbank/pitchbooks.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'Algorithmic Trading Basics', 'Introduction to algo trading', 120, 5, '/courses/algotrading/basics.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'Trading Algorithms', 'Designing trading algorithms', 120, 5, '/courses/algotrading/algorithms.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'Backtesting', 'Backtesting trading strategies', 90, 4, '/courses/algotrading/backtesting.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'High-Frequency Trading', 'HFT concepts and implementation', 120, 5, '/courses/algotrading/hft.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'Risk Controls', 'Risk management in algo trading', 90, 4, '/courses/algotrading/risk.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'Market Microstructure', 'Understanding market structure', 90, 5, '/courses/algotrading/microstructure.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(67, 'Execution Algorithms', 'Advanced execution strategies', 120, 4, '/courses/algotrading/execution.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(68, 'Corporate Finance Strategy', 'Strategic corporate finance', 120, 6, '/courses/corpfinstrat/strategy.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(68, 'Capital Structure Optimization', 'Optimizing capital structure', 90, 6, '/courses/corpfinstrat/capital.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(68, 'Dividend Policy', 'Strategic dividend decisions', 75, 5, '/courses/corpfinstrat/dividend.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(68, 'Corporate Restructuring', 'Financial restructuring strategies', 120, 6, '/courses/corpfinstrat/restructuring.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(68, 'Strategic Investments', 'Making strategic investment decisions', 90, 5, '/courses/corpfinstrat/investments.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(68, 'Value Creation', 'Creating shareholder value', 90, 6, '/courses/corpfinstrat/value.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(69, 'Global Supply Chain Design', 'Designing global supply networks', 120, 7, '/courses/globalsupply/design.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(69, 'International Logistics', 'Managing international logistics', 90, 7, '/courses/globalsupply/logistics.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(69, 'Supply Chain Risk', 'Global supply chain risk management', 90, 6, '/courses/globalsupply/risk.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(69, 'Sustainability', 'Sustainable supply chain practices', 75, 7, '/courses/globalsupply/sustainability.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(69, 'Supply Chain Analytics', 'Advanced analytics for supply chain', 120, 6, '/courses/globalsupply/analytics.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(69, 'Digital Supply Chain', 'Digital transformation in supply chain', 90, 7, '/courses/globalsupply/digital.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(70, 'M&A Process', 'End-to-end M&A process', 120, 8, '/courses/ma/process.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(70, 'Due Diligence', 'Conducting thorough due diligence', 120, 8, '/courses/ma/duediligence.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(70, 'Deal Valuation', 'Valuing M&A targets', 90, 7, '/courses/ma/valuation.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(70, 'Deal Negotiation', 'Negotiating M&A deals', 120, 8, '/courses/ma/negotiation.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(70, 'Integration Planning', 'Post-merger integration', 90, 7, '/courses/ma/integration.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(70, 'Synergy Realization', 'Realizing merger synergies', 75, 8, '/courses/ma/synergy.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(71, 'Java EE Architecture', 'Enterprise Java architecture', 120, 9, '/courses/entjava/architecture.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(71, 'Microservices with Java', 'Building Java microservices', 120, 9, '/courses/entjava/microservices.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(71, 'Performance Optimization', 'Optimizing Java applications', 90, 8, '/courses/entjava/performance.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(71, 'Security Architecture', 'Securing Java applications', 90, 9, '/courses/entjava/security.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(71, 'Scalability Patterns', 'Scaling Java applications', 120, 8, '/courses/entjava/scalability.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(71, 'Cloud-Native Java', 'Java in cloud environments', 90, 9, '/courses/entjava/cloudnative.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(72, 'Big Data Fundamentals', 'Understanding big data', 90, 10, '/courses/bigdata/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(72, 'Hadoop Ecosystem', 'Working with Hadoop', 120, 10, '/courses/bigdata/hadoop.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(72, 'Spark SQL', 'Processing big data with Spark SQL', 120, 9, '/courses/bigdata/sparksql.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(72, 'Data Warehousing', 'Big data warehousing concepts', 90, 10, '/courses/bigdata/warehousing.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(72, 'ETL Processes', 'Extract, Transform, Load at scale', 90, 9, '/courses/bigdata/etl.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(72, 'Big Data Analytics', 'Analytics on big data', 120, 10, '/courses/bigdata/analytics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(73, 'Oracle RAC', 'Real Application Clusters', 120, 11, '/courses/oracledba/rac.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(73, 'Backup and Recovery', 'Advanced backup and recovery', 120, 11, '/courses/oracledba/backup.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(73, 'Performance Tuning', 'Oracle performance tuning', 120, 10, '/courses/oracledba/tuning.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(73, 'Security Management', 'Oracle security administration', 90, 11, '/courses/oracledba/security.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(73, 'High Availability', 'Ensuring Oracle high availability', 90, 10, '/courses/oracledba/ha.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(73, 'Disaster Recovery', 'Oracle disaster recovery', 120, 11, '/courses/oracledba/dr.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'Supervised Learning', 'Supervised ML algorithms', 120, 12, '/courses/ml/supervised.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'Unsupervised Learning', 'Unsupervised ML algorithms', 120, 12, '/courses/ml/unsupervised.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'Deep Learning', 'Neural networks and deep learning', 120, 11, '/courses/ml/deeplearning.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'Model Evaluation', 'Evaluating ML models', 90, 12, '/courses/ml/evaluation.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'Feature Engineering', 'Creating effective features', 90, 11, '/courses/ml/features.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'Model Deployment', 'Deploying ML models to production', 120, 12, '/courses/ml/deployment.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(74, 'ML Operations', 'MLOps best practices', 90, 11, '/courses/ml/mlops.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'Frontend Architecture', 'Modern frontend architecture', 120, 13, '/courses/fullstack/frontend.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'Backend Architecture', 'Scalable backend design', 120, 13, '/courses/fullstack/backend.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'Database Design', 'Full-stack database design', 90, 12, '/courses/fullstack/database.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'API Design', 'Designing RESTful APIs', 90, 13, '/courses/fullstack/api.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'Authentication & Authorization', 'Security in full-stack apps', 120, 12, '/courses/fullstack/auth.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'Deployment & DevOps', 'Full-stack deployment strategies', 90, 13, '/courses/fullstack/deployment.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(75, 'Full-Stack Project', 'Building a complete application', 120, 12, '/courses/fullstack/project.mp4', 7, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(76, 'Executive Coaching Models', 'Advanced coaching frameworks', 120, 14, '/courses/execcoach/models.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(76, 'C-Suite Dynamics', 'Understanding C-level dynamics', 90, 14, '/courses/execcoach/csuite.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(76, 'Leadership Assessment', 'Assessing executive leadership', 90, 13, '/courses/execcoach/assessment.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(76, 'Strategic Coaching', 'Coaching on strategic issues', 120, 14, '/courses/execcoach/strategic.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(76, 'Executive Transitions', 'Coaching during transitions', 75, 13, '/courses/execcoach/transitions.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(76, 'Board Coaching', 'Coaching board members', 90, 14, '/courses/execcoach/board.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(77, 'Stakeholder Mapping', 'Identifying and mapping stakeholders', 90, 15, '/courses/stakeholder/mapping.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(77, 'Stakeholder Analysis', 'Analyzing stakeholder interests', 75, 15, '/courses/stakeholder/analysis.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(77, 'Engagement Strategies', 'Stakeholder engagement plans', 120, 14, '/courses/stakeholder/engagement.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(77, 'Managing Expectations', 'Managing stakeholder expectations', 90, 15, '/courses/stakeholder/expectations.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(77, 'Conflict Resolution', 'Resolving stakeholder conflicts', 90, 14, '/courses/stakeholder/conflict.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(77, 'Communication Plans', 'Stakeholder communication strategies', 75, 15, '/courses/stakeholder/communication.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(78, 'Innovation Frameworks', 'Innovation management frameworks', 90, 16, '/courses/innovation/frameworks.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(78, 'Design Thinking', 'Applying design thinking', 120, 16, '/courses/innovation/designthinking.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(78, 'Disruptive Innovation', 'Managing disruptive innovation', 90, 15, '/courses/innovation/disruptive.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(78, 'Innovation Culture', 'Building innovation culture', 90, 16, '/courses/innovation/culture.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(78, 'Idea Management', 'Managing innovation ideas', 75, 15, '/courses/innovation/ideas.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(78, 'Innovation Metrics', 'Measuring innovation success', 60, 16, '/courses/innovation/metrics.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(79, 'Decision Analysis', 'Structured decision-making', 90, 17, '/courses/decision/analysis.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(79, 'Probability and Risk', 'Probabilistic decision making', 120, 17, '/courses/decision/probability.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(79, 'Scenario Planning', 'Planning for multiple scenarios', 90, 16, '/courses/decision/scenarios.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(79, 'Decision Trees', 'Using decision trees', 75, 17, '/courses/decision/trees.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(79, 'Real Options', 'Real options analysis', 120, 16, '/courses/decision/options.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(79, 'Group Decision Making', 'Facilitating group decisions', 90, 17, '/courses/decision/group.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(80, 'Ethics Foundations', 'Ethical leadership foundations', 90, 18, '/courses/ethics/foundations.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(80, 'Ethical Frameworks', 'Applying ethical frameworks', 75, 18, '/courses/ethics/frameworks.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(80, 'Ethical Dilemmas', 'Resolving ethical dilemmas', 120, 17, '/courses/ethics/dilemmas.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(80, 'Corporate Governance', 'Ethical corporate governance', 90, 18, '/courses/ethics/governance.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(80, 'Whistleblowing', 'Ethical whistleblowing policies', 60, 17, '/courses/ethics/whistleblowing.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(80, 'Ethics Culture', 'Building ethical organizational culture', 90, 18, '/courses/ethics/culture.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(81, 'Quantitative Methods', 'Advanced quantitative techniques', 120, 19, '/courses/quantrisk/methods.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(81, 'VaR Models', 'Value at Risk modeling', 120, 19, '/courses/quantrisk/var.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(81, 'Stress Testing', 'Stress testing methodologies', 90, 18, '/courses/quantrisk/stress.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(81, 'Monte Carlo Simulation', 'Monte Carlo risk simulation', 120, 19, '/courses/quantrisk/montecarlo.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(81, 'Credit Risk Models', 'Quantitative credit risk models', 90, 18, '/courses/quantrisk/creditmodels.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(81, 'Model Validation', 'Risk model validation', 90, 19, '/courses/quantrisk/validation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(82, 'Hedge Fund Structures', 'Understanding hedge fund structures', 120, 20, '/courses/hedgefund/structures.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(82, 'Investment Strategies', 'Hedge fund investment strategies', 120, 20, '/courses/hedgefund/strategies.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(82, 'Long-Short Equity', 'Long-short equity strategies', 90, 19, '/courses/hedgefund/longshort.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(82, 'Event-Driven Strategies', 'Event-driven investing', 90, 20, '/courses/hedgefund/eventdriven.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(82, 'Risk Management', 'Hedge fund risk management', 120, 19, '/courses/hedgefund/risk.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(82, 'Performance Attribution', 'Analyzing hedge fund performance', 75, 20, '/courses/hedgefund/performance.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(83, 'IFRS Framework', 'International accounting framework', 120, 1, '/courses/ifrs/framework.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(83, 'IFRS vs GAAP', 'Comparing IFRS and GAAP', 90, 1, '/courses/ifrs/comparison.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(83, 'Financial Instruments', 'Accounting for financial instruments', 120, 20, '/courses/ifrs/instruments.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(83, 'Revenue from Contracts', 'IFRS 15 revenue recognition', 90, 1, '/courses/ifrs/revenue.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(83, 'Leases', 'IFRS 16 lease accounting', 90, 20, '/courses/ifrs/leases.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(83, 'Consolidation', 'IFRS consolidation standards', 120, 1, '/courses/ifrs/consolidation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(84, 'Sourcing Strategy', 'Developing sourcing strategies', 120, 2, '/courses/sourcing/strategy.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(84, 'Category Management', 'Strategic category management', 90, 2, '/courses/sourcing/category.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(84, 'Supplier Development', 'Developing strategic suppliers', 90, 1, '/courses/sourcing/development.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(84, 'Total Cost of Ownership', 'TCO analysis and optimization', 75, 2, '/courses/sourcing/tco.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(84, 'Global Sourcing', 'Managing global sourcing', 120, 1, '/courses/sourcing/global.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(84, 'E-Sourcing Tools', 'Using e-sourcing platforms', 60, 2, '/courses/sourcing/etools.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(85, 'RegTech Overview', 'Understanding regulatory technology', 90, 3, '/courses/regstrat/overview.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(85, 'Compliance Strategy', 'Strategic compliance planning', 120, 3, '/courses/regstrat/strategy.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(85, 'Regulatory Change Management', 'Managing regulatory changes', 90, 2, '/courses/regstrat/change.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(85, 'Compliance Analytics', 'Using analytics for compliance', 90, 3, '/courses/regstrat/analytics.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(85, 'Third-Party Risk', 'Managing third-party compliance risk', 120, 2, '/courses/regstrat/thirdparty.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(85, 'Regulatory Reporting', 'Strategic regulatory reporting', 75, 3, '/courses/regstrat/reporting.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(86, 'Cloud-Native Principles', 'Principles of cloud-native design', 120, 4, '/courses/cloudnative/principles.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(86, 'Container Orchestration', 'Advanced Kubernetes', 120, 4, '/courses/cloudnative/kubernetes.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(86, 'Service Mesh', 'Implementing service mesh', 90, 3, '/courses/cloudnative/servicemesh.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(86, 'Observability', 'Cloud-native observability', 90, 4, '/courses/cloudnative/observability.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(86, 'Cloud Security', 'Securing cloud-native applications', 120, 3, '/courses/cloudnative/security.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(86, 'GitOps', 'Implementing GitOps workflows', 75, 4, '/courses/cloudnative/gitops.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(87, 'SRE Principles', 'Site Reliability Engineering principles', 90, 5, '/courses/sre/principles.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(87, 'SLOs and SLIs', 'Defining service level objectives', 120, 5, '/courses/sre/slos.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(87, 'Error Budgets', 'Managing error budgets', 75, 4, '/courses/sre/errorbudgets.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(87, 'Incident Management', 'Advanced incident management', 120, 5, '/courses/sre/incidents.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(87, 'Capacity Planning', 'SRE capacity planning', 90, 4, '/courses/sre/capacity.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(87, 'Automation', 'Toil automation strategies', 90, 5, '/courses/sre/automation.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(88, 'Multi-Cloud Architecture', 'Designing multi-cloud solutions', 120, 6, '/courses/multicloud/architecture.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(88, 'Cloud Migration', 'Multi-cloud migration strategies', 120, 6, '/courses/multicloud/migration.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(88, 'Hybrid Cloud', 'Managing hybrid cloud environments', 90, 5, '/courses/multicloud/hybrid.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(88, 'Cloud Cost Management', 'Optimizing multi-cloud costs', 90, 6, '/courses/multicloud/costs.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(88, 'Cloud Governance', 'Multi-cloud governance', 120, 5, '/courses/multicloud/governance.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(88, 'Disaster Recovery', 'Multi-cloud disaster recovery', 90, 6, '/courses/multicloud/dr.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(89, 'Security Architecture', 'Enterprise security architecture', 120, 7, '/courses/advsecurity/architecture.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(89, 'Zero Trust', 'Implementing zero trust security', 120, 7, '/courses/advsecurity/zerotrust.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(89, 'Threat Intelligence', 'Using threat intelligence', 90, 6, '/courses/advsecurity/threat.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(89, 'Security Operations', 'Advanced security operations', 120, 7, '/courses/advsecurity/secops.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(89, 'Incident Response', 'Security incident response', 90, 6, '/courses/advsecurity/incidentresponse.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(89, 'Compliance and Auditing', 'Security compliance and auditing', 90, 7, '/courses/advsecurity/compliance.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(90, 'MLOps Fundamentals', 'Understanding MLOps', 120, 8, '/courses/mlops/fundamentals.mp4', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(90, 'Model Training Pipelines', 'Building ML training pipelines', 120, 8, '/courses/mlops/pipelines.mp4', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(90, 'Model Versioning', 'Managing ML model versions', 75, 7, '/courses/mlops/versioning.mp4', 3, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(90, 'Model Monitoring', 'Monitoring models in production', 90, 8, '/courses/mlops/monitoring.mp4', 4, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(90, 'Model Serving', 'Serving ML models at scale', 120, 7, '/courses/mlops/serving.mp4', 5, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(90, 'MLOps Tools', 'Using MLOps platforms and tools', 90, 8, '/courses/mlops/tools.mp4', 6, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
