CREATE TABLE IF NOT EXISTS lms_schema.LMS_ROLE_DETAILS (
    ROLE_ID INTEGER PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_ROLES (
    EMAIL_ID VARCHAR(100) PRIMARY KEY,
    ROLE_ID INTEGER NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_user_role FOREIGN KEY (ROLE_ID) 
        REFERENCES lms_schema.LMS_ROLE_DETAILS(ROLE_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trainer_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRAINER_DTLS (
    TRAINER_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trainer_id_seq'),
    TRAINER_NAME VARCHAR(100) NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    TRAINER_TYPE VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_SUMMARY (
    TRNG_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_id_seq'),
    TRNG_TOPIC VARCHAR(4000),
    TRNG_DETAILS VARCHAR(4000),
    PRE_REQUISITES VARCHAR(4000),
    LEVEL_CODE VARCHAR(100),
    TRNG_TYPE VARCHAR(20) CHECK (TRNG_TYPE IN ('EXTERNAL', 'INTERNAL')),
    RATING NUMERIC,
    CATEGORY VARCHAR(200),
    TOOLS_NEEDED VARCHAR(4000),
    TECHNOLOGY VARCHAR(500),
    FOLDER_PATH VARCHAR(4000),
    COURSE_PROGRESS INTEGER,
    TRNG_DURATION INTEGER,
    TRAINER_EMAILS VARCHAR(4000),
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_module_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_DTLS (
    MODULE_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_module_id_seq'),
    TRNG_ID INTEGER NOT NULL,
    MODULE_NAME VARCHAR(4000),
    MODULE_DTLS VARCHAR(4000),
    MODULE_DURATION INTEGER,
    TRAINER_ID INTEGER,
    MODULE_PATH VARCHAR(4000),
    SEQ_ID INTEGER,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_training_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_enrl_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING (
    TRNG_ENRL_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_enrl_id_seq'),
    EMAIL_ID VARCHAR(100) NOT NULL,
    TRNG_ID INTEGER NOT NULL,
    STATUS VARCHAR(50),
    ENROLLED_TS TIMESTAMP,
    STARTED_TS TIMESTAMP,
    COMPLETED_TS TIMESTAMP,
    ENROLLMENT_TYPE VARCHAR(20) CHECK (ENROLLMENT_TYPE IN ('VOLUNTARY', 'MANDATORY')),
    ENROLLED_BY_EMAIL_ID VARCHAR(255),
    PROGRESS_PERCENT INTEGER,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_enrollment_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_EMPLOYEE_DTLS(EMAIL_ID),
    CONSTRAINT fk_lms_enrollment_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.trng_enrl_dtl_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_DTLS (
    TRNG_ENRL_DTL_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.trng_enrl_dtl_id_seq'),
    TRNG_ENRL_ID INTEGER NOT NULL,
    MODULE_ID INTEGER NOT NULL,
    STATUS VARCHAR(50),
    TIME_SPENT_SEC INTEGER,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
    CONSTRAINT fk_lms_enrollment_dtls_enrl FOREIGN KEY (TRNG_ENRL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING(TRNG_ENRL_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_enrollment_dtls_module FOREIGN KEY (MODULE_ID) 
        REFERENCES lms_schema.LMS_TRNG_DTLS(MODULE_ID)
);

CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_SEARCH_HIST (
    TRNG_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    VIEW_TS TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TRNG_ID, EMAIL_ID, VIEW_TS),
    CONSTRAINT fk_lms_search_hist_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID),
    CONSTRAINT fk_lms_search_hist_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_EMPLOYEE_DTLS(EMAIL_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_forum_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_FORUM_SUMMARY (
    LMS_TRNG_FORUM_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_forum_id_seq'),
    TRNG_ENRL_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    COMMENTS VARCHAR(4000),
    CREATE_TS TIMESTAMP,
    ACTIVE_FLAG VARCHAR(1) CHECK (ACTIVE_FLAG IN ('Y', 'N')),
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_forum_enrollment FOREIGN KEY (TRNG_ENRL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING(TRNG_ENRL_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_forum_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_USER_ROLES(EMAIL_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_feedback_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_TRNG_FEEDBACK (
    FEEDBACK_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_feedback_id_seq'),
    TRNG_ENRL_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    FEEDBACK_QUES VARCHAR(4000),
    FEEDBACK_RATING INTEGER,
    FEEDBACK_TS TIMESTAMP,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_feedback_enrollment FOREIGN KEY (TRNG_ENRL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING(TRNG_ENRL_ID) ON DELETE CASCADE    
);


CREATE TABLE IF NOT EXISTS lms_schema.LMS_EMPLOYEE_DTLS (
    EMP_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) PRIMARY KEY NOT NULL,
	PASSWRD VARCHAR(255),
	EMP_NAME VARCHAR(200),
	EMP_DESIGNATION VARCHAR(200),
	PROJECT_NAME VARCHAR(500),
	RO_EMAIL_ID VARCHAR(100),
	EMP_ACTIVE_FLAG VARCHAR(1) CHECK (EMP_ACTIVE_FLAG IN ('Y', 'N')),    
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP    
);

CREATE TABLE IF NOT EXISTS lms_schema.LMS_PROJECT_DTLS (
    PROJECT_NAME VARCHAR(500) NOT NULL,
	PM_EMAIL_ID VARCHAR(100) NOT NULL,
	ADM_EMAIL_ID VARCHAR(100) NOT NULL,
	OFFSHORE_DD_EMAIL_ID VARCHAR(100),
	ONSITE_DD_EMAIL_ID VARCHAR(100),
	HRBP_EMAIL_ID VARCHAR(100),
	PROJ_ACTIVE_FLAG VARCHAR(1) CHECK (PROJ_ACTIVE_FLAG IN ('Y', 'N')),    
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP    
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.video_progress_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS lms_schema.LMS_VIDEO_PROGRESS (
    VIDEO_PROGRESS_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.video_progress_id_seq'),
	TRNG_ENRL_DTL_ID INTEGER NOT NULL,
    COMPLETED_FLAG boolean,
    TRNG_ID INTEGER NOT NULL,
	MODULE_ID INTEGER NOT NULL,
	CREATED_AT TIMESTAMP,
	CURRENT_TS NUMERIC(38,2),
	DURATION NUMERIC(38,2),
	LAST_WATCHED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	USER_ID VARCHAR(255),
	WATCH_TIME NUMERIC(38,2),
	MODULE_PROGRESS_PERCENTAGE INTEGER,
    CONSTRAINT FK_TRNG_ENRL_DTL_ID FOREIGN KEY (TRNG_ENRL_DTL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_DTLS(TRNG_ENRL_DTL_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_enrollment_dtls_module FOREIGN KEY (MODULE_ID) 
        REFERENCES lms_schema.LMS_TRNG_DTLS(MODULE_ID)
);

CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRAINER_TRNG_MAPPING (    
	TRNG_ID INTEGER NOT NULL,
	TRAINER_ID INTEGER NOT NULL,
	TRAINER_EMAIL_ID VARCHAR(255),
	TRAINER_NAME VARCHAR(100),
    CONSTRAINT fk_lms_trainer FOREIGN KEY (TRAINER_ID) 
        REFERENCES lms_schema.LMS_TRAINER_DTLS(TRAINER_ID),
	CONSTRAINT fk_lms_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID)
);