CREATE TABLE IF NOT EXISTS lms_schema.LMS_ROLE_DETAILS (
    ROLE_ID INTEGER PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO lms_schema.LMS_ROLE_DETAILS (ROLE_ID, ROLE_NAME) VALUES
(1, 'admin'),
(2, 'lnd'),
(3, 'trainee'),
(4, 'trainer');

CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_ROLES (
    EMAIL_ID VARCHAR(100) PRIMARY KEY,
    ROLE_ID INTEGER NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_user_role FOREIGN KEY (ROLE_ID) 
        REFERENCES lms_schema.LMS_ROLE_DETAILS(ROLE_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trainer_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRAINER_DTLS (
    TRAINER_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trainer_id_seq'),
    TRAINER_NAME VARCHAR(100) NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    TRAINER_TYPE VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_SUMMARY (
    TRNG_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_id_seq'),
    TRNG_TOPIC VARCHAR(1000),
    TRNG_DETAILS VARCHAR(4000),
    PRE_REQUISITES VARCHAR(4000),
    LEVEL_CODE VARCHAR(100),
    TRNG_TYPE VARCHAR(20) CHECK (TRNG_TYPE IN ('EXTERNAL', 'INTERNAL')),
    RATING INTEGER,
    CATEGORY VARCHAR(200),
    TOOLS_NEEDED VARCHAR(4000),
    TECHNOLOGY VARCHAR(500),
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_module_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_DTLS (
    MODULE_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_module_id_seq'),
    TRNG_ID INTEGER NOT NULL,
    MODULE_NAME VARCHAR(1000),
    MODULE_DTLS VARCHAR(4000),
    MODULE_DURATION INTEGER,
    TRAINER_ID INTEGER,
    MODULE_PATH VARCHAR(2000),
    SEQ_ID INTEGER,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_training_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_training_trainer FOREIGN KEY (TRAINER_ID) 
        REFERENCES lms_schema.LMS_TRAINER_DTLS(TRAINER_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_enrl_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING (
    TRNG_ENRL_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_enrl_id_seq'),
    EMAIL_ID VARCHAR(100) NOT NULL,
    TRNG_ID INTEGER NOT NULL,
    STATUS VARCHAR(50),
    ENROLLED_TS TIMESTAMP,
    STARTED_TS TIMESTAMP,
    COMPLETED_TS TIMESTAMP,
    ENROLLMENT_TYPE VARCHAR(20) CHECK (ENROLLMENT_TYPE IN ('VOLUNTARY', 'MANDATORY')),
    ENROLLED_BY_EMAIL_ID VARCHAR(20),
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_enrollment_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_USER_ROLES(EMAIL_ID),
    CONSTRAINT fk_lms_enrollment_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID)
);

CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_DTLS (
    TRNG_ENRL_ID INTEGER NOT NULL,
    MODULE_ID INTEGER NOT NULL,
    STATUS VARCHAR(50),
    CURRENT_LEARNING_TS TIMESTAMP,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TRNG_ENRL_ID, MODULE_ID),
    CONSTRAINT fk_lms_enrollment_dtls_enrl FOREIGN KEY (TRNG_ENRL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING(TRNG_ENRL_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_enrollment_dtls_module FOREIGN KEY (MODULE_ID) 
        REFERENCES lms_schema.LMS_TRNG_DTLS(MODULE_ID)
);

CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_SEARCH_HIST (
    TRNG_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    VIEW_TS TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TRNG_ID, EMAIL_ID, VIEW_TS),
    CONSTRAINT fk_lms_search_hist_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID),
    CONSTRAINT fk_lms_search_hist_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_USER_ROLES(EMAIL_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_forum_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_FORUM_SUMMARY (
    LMS_TRNG_FORUM_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_forum_id_seq'),
    TRNG_ENRL_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    COMMENTS VARCHAR(4000),
    CREATE_TS TIMESTAMP,
    ACTIVE_FLAG VARCHAR(1) CHECK (ACTIVE_FLAG IN ('Y', 'N')),
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_forum_enrollment FOREIGN KEY (TRNG_ENRL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING(TRNG_ENRL_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_forum_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_USER_ROLES(EMAIL_ID)
);

CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_feedback_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS lms_schema.LMS_USER_TRNG_FEEDBACK (
    FEEDBACK_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_feedback_id_seq'),
    TRNG_ENRL_ID INTEGER NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    FEEDBACK_QUES VARCHAR(4000),
    FEEDBACK_RATING INTEGER,
    FEEDBACK_TS TIMESTAMP,
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_feedback_enrollment FOREIGN KEY (TRNG_ENRL_ID) 
        REFERENCES lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING(TRNG_ENRL_ID) ON DELETE CASCADE,
    CONSTRAINT fk_lms_feedback_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_USER_ROLES(EMAIL_ID)
);
