CREATE SEQUENCE IF NOT EXISTS lms_schema.lms_trng_plan_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS lms_schema.LMS_TRNG_PLAN_SUMMARY (
    TRNG_PLAN_ID INTEGER PRIMARY KEY DEFAULT nextval('lms_schema.lms_trng_plan_id_seq'),
    EMAIL_ID VARCHAR(255) NOT NULL,
    TRNG_PLAN_NAME VARCHAR(1000),
    STATUS VARCHAR(50) CHECK (STATUS IN ('DRAFT', 'ACTIVE','INACTIVE')),    
    CREATED_BY VARCHAR(100),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lms_enrollment_user FOREIGN KEY (EMAIL_ID) 
        REFERENCES lms_schema.LMS_EMPLOYEE_DTLS(EMAIL_ID),
    CONSTRAINT fk_lms_enrollment_trng FOREIGN KEY (TRNG_ID) 
        REFERENCES lms_schema.LMS_TRNG_SUMMARY(TRNG_ID)
);

ALTER TABLE lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING 
ADD COLUMN TRNG_PLAN_ID INTEGER;

ALTER TABLE lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING 
ADD COLUMN TRNG_PLAN_SEQ INTEGER;