
BEGIN;

DROP TABLE IF EXISTS lms_schema.LMS_USER_TRNG_FEEDBACK CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_TRNG_FORUM_SUMMARY CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_DTLS CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_TRNG_SEARCH_HIST CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_TRNG_DTLS CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_TRNG_SUMMARY CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_TRAINER_DTLS CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_ROLES CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_ROLE_DETAILS CASCADE;

DROP SEQUENCE IF EXISTS lms_schema.lms_trainer_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trng_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_module_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trng_enrl_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trng_forum_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_feedback_id_seq CASCADE;

COMMIT;
