
BEGIN;

DROP TABLE IF EXISTS lms_schema.LMS_VIDEO_PROGRESS CASCADE;
DROP TABLE IF EXISTS lms_schema.VIDEO_PROGRESS CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_TRNG_FEEDBACK CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_TRNG_FORUM_SUMMARY CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_DTLS CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_TRNG_SEARCH_HIST CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_TRNG_ENROLLMENT_MAPPING CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_TRNG_DTLS CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_TRNG_SUMMARY CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_TRAINER_DTLS CASCADE;
DROP TABLE IF EXISTS lms_schema.LMS_USER_ROLES CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_ROLE_DETAILS CASCADE;

DROP TABLE IF EXISTS lms_schema.LMS_EMPLOYEE_DTLS;
DROP TABLE IF EXISTS lms_schema.LMS_PROJECT_DTLS;

DROP SEQUENCE IF EXISTS lms_schema.video_progress_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trainer_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trng_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.trng_enrl_dtl_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_module_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trng_enrl_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_trng_forum_id_seq CASCADE;
DROP SEQUENCE IF EXISTS lms_schema.lms_feedback_id_seq CASCADE;
--DROP SEQUENCE IF EXISTS lms_schema.lms_trng_feedback_id_seq CASCADE;

COMMIT;
