DELETE FROM LMS_SCHEMA.LMS_TRNG_SUMMARY;
COMMIT;
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Advanced PLSQL','This course provides comprehensive training on advanced Oracle PL/SQL programming techniques. Participants will master hierarchical queries, analytical functions, performance tuning strategies, join methods, and bulk operations. The 10.0-hour program, led by experienced database specialists, equips learners with skills to optimize complex database operations and enhance query performance in enterprise environments.','Basic SQL and database concepts','Advanced',4.88,'Programming / Database','sqldeveloper and Oracle 18c on a server',10,'Advanced PLSQL_SBU1_Dec''23','nishant.soni@irissoftware.com, abhishek.sharma05@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Agile & Scrum','This course provides a complete introduction to Agile and Scrum methodologies for effective project management. Covering three comprehensive sessions, participants learn about Scrum roles, ceremonies, artifacts, requirement management, estimation techniques, and tool implementation. The 6.0-hour training enables teams to adopt Agile practices and improve software delivery through structured frameworks and collaborative approaches.','None','Beginner',4.74,'Project Management','',6,'Agile_Oct 22-SBU1','NA','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Angular Full Stack','This course provides hands-on training in building modern web applications using the Angular framework. Students explore component architecture, dependency injection, forms, routing, observables, NGRX state management, and testing methodologies. The comprehensive 14.0-hour curriculum, delivered by expert frontend developers, prepares participants to create scalable, maintainable web applications with industry-standard practices.','HTML, CSS, and basic JavaScript','Intermediate',4.5,'Programming / Web','1.	Visual studio code
2.	Node JS',14,'Java, UI & (Angular)_Full Stack Journey_Aug'' SBU1''24','sujit.kumar@irissoftware.com, shiv.agarwal@irissoftware.com, sumisha.k@irissoftware.com, aakanksha.pandey@irissoftware.com, ketan.valsangkar@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Angular8','This course provides foundational knowledge of Angular 8 development through theory and practical implementation. Participants learn about Angular architecture, components, templates, data binding, directives, services, form validation, and authentication mechanisms. The 10.0-hour program covers essential concepts needed to build dynamic web applications using Angular 8 framework.','HTML, CSS, and basic JavaScript','Beginner',4.25,'Programming / Web','',10,'Angular 8_Oct 22-SBU1','NA','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Apache Flink','This course provides comprehensive training on Apache Flink for real-time and batch data processing. Students master DataSet and DataStream APIs, transformation operations, watermarks, late element handling, and deployment strategies. The 15.0-hour program covers essential concepts for building scalable streaming applications and processing large-scale data efficiently in distributed environments.','Basics of distributed systems and SQL','Advanced',4.5,'Big Data / Streaming','1. Hardware Requirements
For Each Participant (Local Machine or VM)
Minimum for basic local jobs and development:
●	CPU: Quad-core (4 cores)
●	RAM: 8 GB (16 GB recommended for smooth performance)
●	Disk: 20–30 GB free disk space
●	Network: Stable internet for package downloads and optional cluster setup
For Shared Cluster 
If a multi-node Flink cluster is demonstrated:
●	Master Node:
○	CPU: 4+ cores
○	RAM: 16–32 GB
○	Disk: SSD preferred
●	Worker Nodes:
○	CPU: 4+ cores each
○	RAM: 8–16 GB each
○	Network: LAN or cloud-based setup 
2. Software Requirements
Essential Software (All Machines)
Software	Version / Notes
Java JDK	Java 11 or Java 8 (compatible with Flink)
Apache Flink	Latest stable version (e.g., 1.18.x)
Scala	If using Scala API (2.12 recommended)
Python	If using PyFlink (Python 3.8–3.10)
Maven or Gradle	For building Java/Scala Flink jobs
Docker	For containerized setup (optional but useful)
Kafka (optional)	For streaming data ingestion demos
Git	For version control and sharing examples
IDE	IntelliJ IDEA / VS Code / Eclipse
Browser	Chrome / Firefox – for Flink Web UI access

Network & Access
●	Ports to open (locally or on VMs):
○	Flink JobManager Web UI: 8081
○	Kafka (if used): 9092
○	REST API endpoints: as per setup',15,'iElevate 4 Apache Flink','NA','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('API Automation','This course provides specialized training in API testing and automation methodologies. Participants learn to work with REST and SOAP APIs, implement authentication mechanisms, handle serialization/deserialization, and utilize tools like Postman and Swagger. The comprehensive curriculum covers framework development, JSON manipulation, and best practices for creating robust API automation solutions.','Core Java (OOPs, collections)','Intermediate',4.67,'Quality Engineering','postman, intellid idea or eclipse , java (JDK)',12.5,'API Automation_Nov''23_SBU1_CDP','ankit.shah01@irissoftware.com, jitendra.khedar@irissoftware.com, ruchira.shukla@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Automation Devops','This course provides essential knowledge of automation concepts and DevOps practices. Students learn operating system fundamentals, shell scripting, database concepts, and build automation techniques. The program emphasizes practical skills in automation workflows, scripting languages, and foundational DevOps principles necessary for modern software development environments.','Basic Linux/CLI and Git','Beginner',4.72,'DevOps','',3,'Automation Devops_Oct''23_SBU1_CDP','amit.sharma03@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('AWS','This course provides comprehensive introduction to Amazon Web Services and cloud computing fundamentals. Participants explore key AWS services including IAM, EC2, S3, and RDS, along with billing management, security policies, and console navigation. The training covers essential cloud concepts and hands-on experience with AWS infrastructure services for modern application deployment.','Basic Linux/CLI and Git','Beginner',4.85,'Cloud Computing','',10,'AWS_SBU1_Feb''24','astha.jain@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('BDD Framework Automation','This course provides in-depth training on Behavior-Driven Development using Cucumber framework. Students learn to create feature files, write step definitions, implement page object models, and integrate with TestNG. The curriculum covers framework components, hooks, tags, parallel execution, and reporting mechanisms essential for effective BDD automation implementation.','Basic Java and testing concepts','Beginner',4.78,'Quality Engineering','Eclipse Photon and JDK 1.8 ',6,'BDD Framework_SBU1_Jan''24','srinivasan.p@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Big Data with Spark','This course provides comprehensive understanding of Big Data principles and Apache Spark implementation. Participants explore data storage, processing techniques, Spark applications, and Hive integration. The training covers characteristics of Big Data, associated risks and benefits, practical applications, and hands-on laboratory exercises to understand the impact of Big Data technologies on modern IT infrastructure.','Basics of distributed systems and SQL','Intermediate',4.7,'Big Data','Hadoop server with all the components installed(Hadoop, hive, spark, impala, sqoop, oracle db) with read/write access on the server. And Putty',12.5,'Big Data_SBU1_Feb''24','pankaj.bhandari@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Bit Bucket / Git Understanding','This course provides essential training in version control systems using Git and BitBucket platforms. Students learn repository management, basic Git commands, branching strategies, commit management, and pull request workflows. The program equips participants with fundamental skills needed for collaborative software development and code version management in team environments.','Basic Linux/CLI and Git','Beginner',4.61,'DevOps / Source Control','Git & Bit Bucket any version',6,'Git & Bit Bucket_SBU1_Jan''24','nitesh.dubey@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Build Management','This course provides comprehensive knowledge of build management processes and automation techniques. Participants learn build identification, definition, execution strategies, reporting mechanisms, and metrics analysis. The curriculum covers automated build systems, Maven implementation, SonarQube integration, and best practices for continuous integration and deployment pipelines.','Java basics and Git','Beginner',4.53,'DevOps','Java 11 JDk and Eclipse',4,'Build Management_Oct''23_SBU1_CDP','joginder.kumar@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Confluence & Jira Tool','This course provides practical training on Atlassian Jira and Confluence platforms for project management and documentation. Students learn ticket creation, dashboard configuration, JQL queries, bulk operations, and integration techniques. The comprehensive training covers advanced filtering, report generation, and traceability matrix implementation for effective project tracking and collaboration.','None','Beginner',4.61,'Project Management','',4,'Confluence & Jira_Jul''23_SBU1_CDP','sonam.kaushal@irissoftware.com, rahul.malkoti@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Datawarehousing & Snowflake','This course provides foundational knowledge of data warehousing concepts and Snowflake cloud platform architecture. Participants explore data warehousing principles, Snowflake''s unique architecture, and basic Informatica integration techniques. The training prepares students for modern cloud-based data warehousing solutions and analytical data processing.','SQL basics','Beginner',4.55,'Database / ETL','',10,'Datawarehousing & Snowflake_SBU1_Dec''23','nishant.chauhan@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Docker & Kubernetes','This course provides comprehensive training on containerization using Docker and orchestration with Kubernetes. Students learn container concepts, Docker image management, registry operations, networking, volume management, and Kubernetes fundamentals. The curriculum covers essential skills for modern application deployment, scaling, and container orchestration in cloud environments.','Basic Linux/CLI and Git','Beginner',4.49,'DevOps / Cloud','',40,'Docker & Kubernetes_Sep 22-SBU1_Batch1','NA','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('GenAI','This course provides comprehensive introduction to Generative Artificial Intelligence and its applications. Participants explore AI types, machine learning fundamentals, deep learning concepts, natural language processing, and Python implementation. The training covers word embeddings, neural networks, prompt engineering, vector databases, and practical LLM project development for real-world AI applications.','Python basics and linear algebra fundamentals','Advanced',4.3,'Artificial Intelligence','',24,'iElevate_Gen AI_Sep 24_SBU1','nipun.kansal@irissoftware.com, vemala.obireddy@irissoftware.com, ayushi.gupta@irissoftware.com, varun.sharma@irissoftware.com, chanchal.shukla@irissoftware.com, chitragandha.chute@irissoftware.com, ','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Git & BitBucket','This course provides fundamental training in Git version control system and BitBucket platform integration. Students learn repository creation, basic Git commands, change management, branching strategies, and pull request workflows. The program establishes essential version control skills necessary for collaborative software development and code management practices.','Basic Linux/CLI and Git','Beginner',4.38,'DevOps / Source Control','Git & Bit Bucket any version',6,'Git & Bit Bucket_Jun''23_SBU1_CDJ','nitesh.dubey@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Hive','This course provides comprehensive training on Apache Hive for big data processing and analytics. Participants learn Hive architecture, internal data flow mechanisms, data types, partitioning strategies, bucketing concepts, and user-defined functions. The practical curriculum includes hands-on experience with database creation, table operations, joins, and standard functions for effective data analysis.','SQL basics','Intermediate',4.42,'Big Data','',7.5,'Hive_Jul''23_SBU1_CDP','pankaj.bhandari@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Java 17','This course provides updated knowledge of modern Java features from versions 9 through 17. Students explore Java release cycles, reactive streams, JVM enhancements, and language improvements introduced in recent versions. The training prepares developers to leverage modern Java capabilities and understand the evolution of the Java platform for contemporary application development.','Core Java (OOPs, collections)','Intermediate',4.5,'Programming','•	JAVA JDK 11
•	IntelliJ
•	Maven
Java 17',21,'iElevate 4_Java_Sep''25_SBU1','nipun.batra@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Java Collections & Streams API','This course provides in-depth training on Java Collections framework and Streams API functionality. Participants master List, Set, Queue, and Map interfaces, along with their implementation classes and common operations. The curriculum covers Java Optionals, Stream operations, and practical applications of collections and streams in modern Java development.','Core Java (OOPs, collections)','Intermediate',4.7,'Programming','Eclipse/IntelliJ , Java 8 or above, Maven',6,'Java Collections_SBU1_Jan''24','siddharth.singh@irissoftware.com, vikas.tewari@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Java Full Stack','This course provides comprehensive training in end-to-end Java application development. Students learn Java fundamentals, object-oriented programming, J2EE patterns, data structures, algorithms, Spring framework, microservices, Hibernate ORM, and REST API development. The extensive 30.0-hour program prepares developers for full-stack Java enterprise application development with modern technologies and best practices.','Core Java (OOPs, collections), basic SQL','Beginner',4.6,'Programming / Full Stack','•	JAVA JDK 11
•	IntelliJ
•	Maven',30,'UI, (Java) & Database_Full Stack Journey_Oct'' SBU1''24','rajeesh.k@irissoftware.com, shivam.gupta@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Jenkins','This course provides practical training on Jenkins continuous integration and automation platform. Participants learn Jenkins integration with Selenium frameworks, test suite execution, job parameterization, GitHub integration, and automated reporting. The training covers essential CI/CD pipeline concepts and automated testing workflows for modern software development practices.','Basic Git and Maven/Gradle','Beginner',4.94,'DevOps / Automation','',4,'Jenkins_Jun''23_SBU1_CDJ','madhu.babu@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Kafka','This course provides comprehensive understanding of Apache Kafka distributed messaging system. Students explore Kafka architecture, producer-consumer models, operational concepts, Kafka Connect functionality, and storage semantics. The training prepares participants to implement robust messaging solutions and understand distributed streaming platforms for real-time data processing applications.','Basics of distributed systems and Java','Beginner',4.46,'Big Data / Messaging','Java 11 JDk and Eclipse',10,'Kafka_Oct''23_SBU1_CDP','nikhil.batra@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Microservices','This course provides advanced training in microservices architecture and implementation strategies. Participants learn decomposition techniques, design patterns, deployment scenarios, service mesh concepts, inter-service communication, transaction management, and scaling strategies. The comprehensive curriculum covers practical microservices implementation with modern tools and architectural best practices for distributed systems.','Core Java, Spring basics, REST fundamentals','Advanced',4.7,'Programming','Java 11 Spring Tool Suite - v4 Git Bash Docker - Latest Apache Kafka',16,'iElevate 4_Microservices_Aug''25_SBU1','amit.bhagra@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Multithreading','This course provides specialized training in Java multithreading and concurrent programming concepts. Students explore thread creation, java.util.concurrent APIs, performance optimization techniques, concurrency challenges, advanced locking mechanisms, and asynchronous programming patterns. The training equips developers with essential skills for building high-performance, thread-safe Java applications.','Core Java (OOPs, collections)','Advanced',4.77,'Programming','• JAVA JDK 11 or JAVA JDK 8
• IntelliJ or Eclipse',9,'Multithreading_SBU1_Jan''24','nipun.batra@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Oracle Full Stack','This course provides comprehensive training in Oracle database development and SQL programming. Participants learn database storage concepts, constraints, SQL statements, complex joins, subqueries, analytical functions, stored procedures, triggers, packages, and security management. The extensive curriculum prepares students for complete Oracle database application development and administration.','SQL basics','Beginner',4.7,'Database','',28,'Oracle_Full Stack Journey_Nov'' SBU1''24','saurabh.kanoongo@irissoftware.com, ashwin.dev@irissoftware.com, simpy.kumari@irissoftware.com, balakumaran.arumugam@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Power BI','This course provides comprehensive training in Microsoft Power BI for business intelligence and data visualization. Students explore BI concepts, Power BI architecture, report creation, dashboard development, data transformation, security implementation, and advanced analytics features. The training prepares participants to create effective business intelligence solutions and data-driven insights for organizational decision-making.','Familiarity with data and Excel/CSV','Beginner',4.66,'Data Visualization','Power BI desktop application',10,'Power BI_SBU1_Feb''24','sakshi.bansal@irissoftware.com, vikas.jayara@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Python','This course provides foundational training in Python programming language and development practices. Participants learn Python data types, object-oriented programming concepts, version control, file operations, collections, database connections, debugging techniques, and project management. The comprehensive curriculum establishes essential Python skills for software development and automation tasks.','Basic programming concepts and Python setup','Intermediate',4.7,'Programming','Pyton 3.12 & VS Code',20,'iElevate 4_Python_Aug''25_SBU1','prakash.pandey@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('React Full Stack','This course provides comprehensive training in React framework for modern web application development. Students explore React fundamentals, component architecture, state management, hooks, forms, routing, authentication, API integration, testing methodologies, and styling approaches. The extensive curriculum prepares developers to build scalable, interactive web applications using contemporary React development practices.','HTML, CSS, and basic JavaScript','Beginner',4.9,'Programming / Web','',20,'React_Full Stack Journey_Nov'' SBU1''24','shiv.agarwal@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Report Publishing (Automation)','This course provides specialized training in extent report implementation within Selenium automation frameworks. Participants learn fundamental to advanced techniques for generating comprehensive test reports, integrating reporting mechanisms, and enhancing test automation frameworks with professional reporting capabilities for better test result communication and analysis.','Basic Java and Selenium basics','Beginner',4.7,'Quality Engineering','',4,'Report Publishing_Nov''23_SBU1_CDP','sajjan.barla@irissoftware.com, nitin.kumar05@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('RPA Advanced','This course provides advanced training in Robotic Process Automation using UiPath platform. Students master automation events, data scraping techniques, Excel/PDF/Citrix/Outlook automation, ReFramework implementation, and Orchestrator management. The comprehensive curriculum includes practical use cases, assessments, and advanced automation strategies for enterprise process automation solutions.','Windows basics; UiPath Community Edition','Advanced',4.58,'Automation','UI Path',10,'RPA Advanced_Aug''23_SBU1_CDP','ravindra.bhadoriya@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('SDLC Models','This course provides comprehensive understanding of Software Development Life Cycle methodologies and processes. Participants explore planning phases, requirements analysis, system design, development approaches, deployment strategies, and maintenance procedures. The training covers project planning, scope definition, feasibility studies, and various SDLC models essential for effective software project management and execution.','None','Advanced',4.83,'Software Development','',1.5,'SDLC_Oct''23_SBU1_CDP','alok.bansal@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Selenium & Test NG','This course provides practical training in Selenium automation testing using Java and TestNG framework. Students learn automation framework design, page object model implementation, TestNG annotations, reporting mechanisms, and browser automation techniques. The curriculum prepares participants to build robust, maintainable automation frameworks for web application testing.','Core Java (OOPs) and Selenium basics','Intermediate',4.91,'Quality Engineering','Eclipse, Maven, TestNG plugin in eclipse, Chromedriver, JDK 1.8',10,'Selenium & Test NG_SBU1_Dec''23','mahesh.gupta@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Tableau','This course provides comprehensive training in Tableau for data visualization and business analytics. Participants learn Tableau fundamentals, advanced visualization techniques, dashboard creation, interactive filtering, calculated fields, mapping capabilities, and sharing mechanisms. The training prepares students to create compelling data stories and analytical dashboards for business intelligence applications.','Familiarity with data and Excel/CSV','Beginner',4.55,'Data Visualization','',10,'Tableau_Jul''23_SBU1_CDP','vipin.mittal@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Tableau Advanced','This course provides advanced training in sophisticated Tableau features and enterprise capabilities. Students explore data modeling techniques, Hyper file optimization, row-level security implementation, virtual connections, data storytelling, and Tableau''s data guide functionality. The specialized curriculum prepares experienced users to leverage advanced Tableau features for complex analytical requirements.','Tableau fundamentals','Advanced',4.59,'Data Visualization','',7.5,'Tableau Advanced_Sep''23_SBU1_CDP','naresh.sharma@irissoftware.com, abhijeet.srivastava@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Test Management','This course provides comprehensive training in software test management processes and methodologies. Participants learn test planning strategies, documentation standards, estimation techniques, risk assessment, review processes, team dynamics, and process improvement approaches. The curriculum covers essential skills for managing testing activities and leading quality assurance initiatives in software development projects.','Testing fundamentals','Intermediate',4.63,'Quality Engineering','',6,'Test Management_SBU1_Feb''24','nipun.grover@irissoftware.com, sanjeev.kumar@irissoftware.com, millanpreet.kaur@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Testing Software Quality Metrics','This course provides specialized training in measurement programs and quality metrics for software testing. Students explore measurement concepts, requirements traceability matrix implementation, testing metrics analysis, and practical case studies. The focused curriculum prepares quality assurance professionals to implement effective measurement strategies and improve testing processes through data-driven approaches.','Testing fundamentals','Intermediate',4.46,'Quality Engineering','Eclipse',3,'Testing Quality Metrics_Feb''24_SBU1_CDP','geetha.panneerselvam@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('UI Automation','This course provides comprehensive training in web user interface automation using Selenium WebDriver. Participants learn various locator strategies, WebDriver commands, wait mechanisms, exception handling, file upload automation, multi-window management, and JavaScript executor implementation. The practical curriculum includes TestNG integration and best practices for robust UI automation framework development.','Core Java and Selenium basics','Beginner',4.4,'Quality Engineering','eclipse or intellij idea (editor) & jdk 1.8
Java version
AutoIT - https://www.autoitscript.com/site/autoit/downloads/',17.5,'UI Automation_Project Training_SBU1''24','ankit.shah01@irissoftware.com; jitendra.khedar@irissoftware.com; akanksha.chhabra@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('UI Full Stack','This course provides comprehensive training in modern user interface development technologies and practices. Students explore JavaScript fundamentals, ES6 features, TypeScript introduction, CSS preprocessors, Bootstrap framework, asynchronous programming, error handling, and Node.js tooling. The extensive curriculum prepares developers for full-stack UI development with contemporary web technologies and best practices.','HTML, CSS, and basic JavaScript','Beginner',4.7,'Programming / Web','Visual Studio Code & Node JS',20,'Java, (UI) & React_Full Stack Journey_Oct'' SBU1''24','aakanksha.pandey@irissoftware.com, ashish.mishra01@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO LMS_SCHEMA.LMS_TRNG_SUMMARY (TRNG_TOPIC, TRNG_DETAILS, PRE_REQUISITES, LEVEL_CODE, RATING, CATEGORY, TOOLS_NEEDED, TRNG_DURATION, FOLDER_PATH,TRAINER_EMAILS, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS) VALUES ('Unit Testing - Jasmine Karma','This course provides specialized training in Angular unit testing using Jasmine and Karma frameworks. Participants learn testing setup, component testing, service testing, form testing, pipe and directive testing, debugging techniques, and code coverage analysis. The comprehensive curriculum prepares Angular developers to implement thorough unit testing strategies and maintain high-quality code standards.','Angular basics, Node.js tooling','Beginner',4.7,'Programming','Visual Studio Code & Node JS',2,'Java & Angular(unit Testing)_Full Stack Journey_SBU1''24','ashish.pal@irissoftware.com','SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
COMMIT;